config/routes.rb
Rails.application.routes.draw do
  root to: 'uploads#index'
  devise_for :users

  resources :users
  resources :uploads

end

app/models/upload.rb
class Upload < ActiveRecord::Base

  include Rails.application.routes.url_helpers

  has_attached_file :picture,
    styles: { :medium => "300x300>", :thumb => "100x100>" },
    storage: :s3,
    s3_credentials: { bucket: 'login_app' }

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  belongs_to :user

  def to_jq_upload
    {
        'name' => read_attribute(:picture_file_name),
        'size' => read_attribute(:picture_file_size),
        'url' => picture.url(:original),
        'delete_url' => upload_path(self),
        'delete_type' => 'DELETE',
        'thumbnail_url' => picture.url(:thumb)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :uploads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user!

  def index
    @uploads = current_user.uploads
    @user = current_user
    respond_to do |format|
      format.html
      format.json { render json: @uploads.map{|upload| upload.to_jq_upload } }
    end
  end

  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  def edit
    @upload = Upload.find(params[:id])
  end

  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        current_user.uploads << @upload
        format.html {
          render :json => [@upload.to_jq_upload].to_json,
                 :content_type => 'text/html',
                 :layout => false
        }
        format.json { render json: {files: [@upload.to_jq_upload]}, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
  def upload_params
    params.require(:upload).permit(:picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      <ul>
      #{messages}
      </ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loginapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <% if notice %>
      <div class='container'>
        <div class='row'>
          <div class='alert alert-info alert-dismissable'>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= notice %>
          </div>
        </div>
      </div>
    <% elsif alert %>
      <div class='container'>
        <div class='row'>
          <div class='alert alert-danger alert-dismissable'>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= alert %>
          </div>
        </div>
      </div>
    <% end %>
<%= yield %>
  </div>
</div>
</body>
</html>

app/views/uploads/index.erb
  <% if current_user && @uploads%>
    <div class='row'>
      <% @uploads.each do |u| %>
        <div class='col-lg-2'>
        <a href=<%= u.picture.url %> class="thumbnail" >
            <%= image_tag u.picture.url(:medium) %>
        </a>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class='row'>
    <div class='col-lg-2 col-lg-offset-5'>
      <%= link_to 'Upload image', new_upload_path, class: 'btn btn-primary'%>
    </div>
  </div>
&nbsp;
  <div class="jumbotron">
    <div class='row'>
      <div class='col-lg-2'>
        <%= gravatar_tag @user.email, :size => 128 %>
      </div>
      <div class='col-lg-3'>
        <p>
          Email:
          <%= @user.email %>
        </p>
        <p>
          Registered on:
          <%= @user.created_at.to_date %>
        </p>
        <p>
          <%= link_to 'Log out', destroy_user_session_path, class: 'navbar-link', method: 'delete' %>
        </p>
      </div>
    </div>
    <div class='row'>
      <div class='col-lg-2'>
        <%= link_to '[Edit information]', edit_user_registration_path %>
      </div>
    </div>
  </div>

app/views/uploads/new.erb
  <h2>Upload images</h2>
  <%= form_for Upload.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="col-lg-6"> <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <span>Add files...</span>
          <%= f.file_field :picture, name: 'upload[picture]'%>
        </span>
        <button type="submit" class="btn btn-primary start">
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <span>Delete</span>
        </button>
      </div>
      <div class="col-lg-4">
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

</div>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload();
    $.getJSON($('#fileupload').prop('action'), function (files) {
      var fu = $('#fileupload').data('blueimpFileupload');
      fu._adjustMaxNumberOfFiles(-files.length);
      console.log(files);
      template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
      // Force reflow:
      fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
      template.addClass('in');
      $('#loading').remove();
    });
  });
</script>